platform :ios, '13.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

prepare_react_native_project!

# flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  # use_frameworks! :linkage => linkage.to_sym
end

target 'Todorant' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # :flipper_configuration => flipper_config,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Siri', :path => "#{permissions_path}/Siri"
  
  pod 'simdjson', path: '../node_modules/@nozbe/simdjson', modular_headers: true
  
  post_install do |installer|
    react_native_post_install(
      installer,
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

target 'TodorantToday' do
  pod 'Alamofire'
  pod 'SwiftKeychainWrapper'
end

target 'TodorantHomescreen' do
  pod 'Alamofire'
  pod 'SwiftKeychainWrapper'
end

target 'TodorantIntents' do
  pod 'Alamofire'
  pod 'SwiftKeychainWrapper'
end

target 'Todorant-watchOS Extension' do
  platform :watchos, '7.0'
  pod 'Alamofire'
  pod 'KeychainAccess'
end
