default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  lane :commit_and_push_ios_release do
    git_add
    git_commit(
      message: "ios release"
    )
    push_to_git_remote
  end

  lane :release do
    increment_version_number
    increment_build_number
    build_app(
      scheme: "Todorant",
      silent: true
    )
    upload_to_app_store(
      submit_for_review: true,
      skip_metadata: true,
      skip_screenshots: true,
      automatic_release: true,
      submission_information: {
        export_compliance_uses_encryption: false,
        add_id_info_uses_idfa: false
      }
    )
    commit_and_push_ios_release
  end
end