#!/usr/bin/ruby

default_platform :ios

platform :ios do
  lane :commit_and_push_ios_release do
    git_add
    git_commit(
      message: "ios release",
      path: "."
    )
    push_to_git_remote
  end

  lane :commit_and_push_ios_release_beta do
    git_add
    git_commit(
      message: "ios beta release",
      path: "."
    )
    push_to_git_remote
  end

  lane :frame do
    frameit(
      path: './fastlane/screenshots'
    )
  end

  lane :build_for_sumbission do
    cocoapods
    increment_build_number
    build_app(
      export_xcargs: "-allowProvisioningUpdates",
      scheme: "Todorant",
      silent: true
    )
  end

  lane :release do
    increment_version_number
    build_for_sumbission
    upload_to_app_store(
      submit_for_review: true,
      skip_screenshots: true,
      submission_information: {
        add_id_info_uses_idfa: true,
        add_id_info_limits_tracking: false,
        add_id_info_serves_ads: false,
        add_id_info_uses_idfa: false,
        add_id_info_tracks_install: false,
        add_id_info_uses_idfa: false,
        export_compliance_available_on_french_store: "",
        export_compliance_contains_proprietary_cryptography: "",
        export_compliance_contains_third_party_cryptography: "",
        export_compliance_uses_encryption: true,
        export_compliance_is_exempt: true,
        export_compliance_encryption_updated: false,
        uses_non_exempt_encryption: false
      },
      force: true,
    )
    commit_and_push_ios_release
  end

  lane :release_beta do
    build_for_sumbission
    upload_to_testflight(
      distribute_external: true,
      expire_previous_builds: true,
      changelog: "Bugfixes",
      groups: "External",
    )
    commit_and_push_ios_release_beta
  end

  lane :upload_screenshots do
    upload_to_app_store(
      submit_for_review: false,
      skip_screenshots: false,
      automatic_release: false,
      skip_metadata: true,
      skip_binary_upload: true,
      overwrite_screenshots: true,
    )
  end

  lane :take_and_upload_screenshots do
    cocoapods
    capture_screenshots
    frame
    upload_screenshots
  end
end