#!/usr/bin/ruby

default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  lane :commit_and_push_ios_release do
    git_add
    git_commit(
      message: "ios release",
      path: "."
    )
    push_to_git_remote
  end

  lane :frame do
    frameit(
      path: './fastlane/screenshots'
    )
  end

  lane :release do
    increment_version_number
    increment_build_number
    build_app(
      scheme: "Todorant",
      silent: true
    )
    upload_to_app_store(
      submit_for_review: true,
      skip_screenshots: false,
      automatic_release: true,
      submission_information: {
        export_compliance_available_on_french_store: "",
        export_compliance_contains_proprietary_cryptography: "",
        export_compliance_contains_third_party_cryptography: "",
        export_compliance_uses_encryption: true,
        export_compliance_is_exempt: true,
        export_compliance_encryption_updated: false
      }
    )
    commit_and_push_ios_release
  end

  lane :upload_screenshots do
    upload_to_app_store(
      submit_for_review: false,
      skip_screenshots: false,
      automatic_release: false,
      skip_metadata: true,
      skip_binary_upload: true,
      overwrite_screenshots: true,
    )
  end

  lane :take_and_upload_screenshots do
    capture_screenshots
    frame
    upload_screenshots
  end
end