default_platform(:android)

platform :android do
  desc "Build debug and test APK for screenshots"
  lane :build_for_screengrab do
    gradle(
      task: 'clean'
    )
    build_android_app(
      task: 'app:assembleDebug',
    )
    build_android_app(
      task: 'app:assembleAndroidTest',
      flags: '-DtestBuildType=debug'
    )
  end

  lane :take_screenshots do
    capture_android_screenshots
  end

  lane :upload_screenshots do
    supply(
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true
    )
  end

  lane :screenshots do
    build_for_screengrab
    take_screenshots
    upload_screenshots
  end

  lane :release do
    gradle(
      task: 'bundle',
      build_type: 'Release'
    )
    supply(
      skip_upload_apk: true,
      aab: './app/build/outputs/bundle/release/app.aab'
    )
  end
end
