name: Todorant Workflows
on:
  pull_request:
    types: [synchronize, opened]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install yarn 3
        run: yarn policies set-version 3.2.0
      - name: Install modules
        run: yarn
      - name: Compile code
        run: yarn tsc --skipLibCheck
      - name: Lint
        run: yarn lint
