name: Todorant Workflows
on:
  pull_request:
    types: [synchronize, opened]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@3.2.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@3.2.0
        with:
          cmd: yarn tsc --skipLibCheck
      - uses: borales/actions-yarn@3.2.0
        with:
          cmd: yarn lint
