name: Todorant Workflows
on:
  pull_request:
    types: [synchronize, opened]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0

      - name: Setup Node environment
        uses: actions/setup-node@v3.0.0
        with:
          cache: yarn
          node-version-file: .nvmrc

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run yarn tsc --skipLibCheck
